### ISSUE TITLE
Discrepancy in location of repository on Android Arsenal

### ISSUE THREAD

**Issue by DanielSims1** [PicnicSupermarket/FingerPaintView#1]
On [Android Arsenal](https://android-arsenal.com/details/1/6715#!description) under [Description] ,

Instructions for adding the reference to your build.gradle shows an incorrect repository location: 

>dependencies {
 >...
 >compile **'com.github.picnic:FingerPaintView:1.0.0'**
>}

While under [Package]

The correct repository location is shown:

>dependencies {
>    compile **'com.github.PicnicSupermarket:FingerPaintView:1.0'**
>}

**Comment by luisfuertes** [comment]
Thanks @DanielSims1 

And route for Layout is `tech.picnic.fingerpaintview.FingerPaintImageView` instead of `nl.picnic.fingerpaintview.FingerPaintImageView`
