### ISSUE TITLE
Gradle sync fail v1.1

### ISSUE THREAD

**Issue by MFam** [PicnicSupermarket/FingerPaintView#10]
Hi,

I want to use your library.

Create a new project to add the FingerPaintView library.
But,

ERROR: Failed to resolve: com.github.PicnicSupermarket:FingerPaintView:1.1
Show in Project Structure dialog
Affected Modules: app

Gradle sync fail.

I use Android studio.
minSdkVersion 21
targetSdkVersion 29
versionCode 1
versionName "1.0"

distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip

Plz, Check

**Comment by watanabethais** [comment]
I wanted to use the library too but in JitPack it is building with errors.
https://jitpack.io/com/github/PicnicSupermarket/FingerPaintView/1.1/build.log

Could someone check?
Thank you!

**Comment by johnaziz57** [comment]
@MFam @watanabethais, I have updated the gradle version, it should work now, please notify us, if the issue persists

**Comment by watanabethais** [comment]
@johnaziz57 I'm still getting error when adding to my project... maybe in JitPack hasn't updated yet.

**Comment by johnaziz57** [comment]
@watanabethais Will check it again, I am sorry if we are a little busy these days

**Comment by watanabethais** [comment]
@johnaziz57 No problem. Thanks for the help even in busy days.

**Comment by johnaziz57** [comment]
Really sorry guys for very very late response, but I have noticed that I didn't publish a new version because the commit wasn't tagged
I have tagged the latest commit with 1.2
If you are still facing this problem could you please try again

**Comment by johnaziz57** [comment]
I will mark this issue as closed for now then
