### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [PicnicSupermarket/FingerPaintView#3]
Good day Sir I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before i begin my design. Hoping for your positive feedback. Thanks

**Comment by Stephan202** [comment]
Hi @mansya, thanks for your kind offer! While we appreciate your enthusiasm, we won't need help with logo and icon development. We have a whole team of dedicated designers taking great pride in creating such visual assets for our company.

Have a new weekend!
